### ISSUE TITLE
Remove venv folders

### ISSUE THREAD

**Issue by bradbeattie** [Cronza/GVNEngine#4]
Just skimming over the code base out of curiosity. Noticed your full venv folders were included in the repo (e.g. https://github.com/Cronza/GVNEngine/blob/master/GVNEditor/venv/Scripts/pip.exe). Environments aren't usually included directly in Python repos, but instead their requirements are enumerated either in setup.py (for production-ready packages) or more commonly as a text file (see https://pip.pypa.io/en/stable/user_guide/#requirements-files, or https://github.com/pygame/pygameweb/blob/master/requirements.txt as an example of another project doing just this).

I'd recommend two files replace each of your venv directories:

**requirements.core** pinned at major versions, written by you. Example:
```
click==7
pygame==2
PyQt5==5
```

**requirements.txt** autogenerated after you `pip install -r requirements.core --upgrade; pip freeze -r requirements.txt`, pinning specific versions for reproducibility. Example generated from the above requirements.core:
```
click==7.1.2
pygame==2.0.1
PyQt5==5.15.3
PyQt5-Qt==5.15.2
PyQt5-sip==12.8.1
```

It's possible to just get away with just requirements.txt, but it's easy to forget what you intended to install, and what got installed on your behalf.

**Comment by bradbeattie** [comment]
Feel free to ignore/close this as the ramblings of a withering mind. :P

**Comment by Cronza** [comment]
Removed the venv folders from the dev branch, and replaced them with `requirements.txt` files. Ran a local test in a new clone and it was quick and easy to set up!

Thank you for the suggestion @bradbeattie 🙏 I never knew much about requirements.txt files, so this was a perfect excuse to learn about them
